service: serverless-slack

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "=1.7.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage, self:custom.defaultStage}
  profile: serverless-slack
  region: us-east-1
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sdb:PutAttributes"
        - "sdb:Select"
      Resource: "arn:aws:sdb:${self:provider.region}:*:domain/serverless-slack-iot"
    - Effect: "Allow"
      Action:
        - "iot:DescribeEndpoint"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sts:AssumeRole"
      Resource: "*"

functions:
  iotKeys:
    handler: handler.iotKeys
    events:
      - http:
          path: iot/keys
          method: get

custom:
  defaultStage: dev
  webpackIncludeModules: true # enable auto-packing of external modules

plugins:
  - serverless-webpack
